server:
  port: 9999
spring:
  devtools:
    restart:
      enabled: true  #设置开启热部署
  redis:
    host: ilego.club
    #host: 192.168.88.255
    port: 6379
    timeout: 20000
    #    集群环境打开下面注释，单机不需要打开
    #    cluster:
    #      集群信息
    #      nodes: xxx.xxx.xxx.xxx:xxxx,xxx.xxx.xxx.xxx:xxxx,xxx.xxx.xxx.xxx:xxxx
    #      #默认值是5 一般当此值设置过大时，容易报：Too many Cluster redirections
    #      maxRedirects: 3
    pool:
      max-active: 8
      min-idle: 0
      max-idle: 8
      max-wait: -1
    password:
    database: 0

  datasource:
    #driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://ilego.club:3306/xiaoliu_manager
    username: lx
    password: lx123
  freemarker:
      allow-request-override: false
      cache: false
      check-template-location: true
      charset: UTF-8
      content-type: text/html; charset=utf-8
      expose-request-attributes: false
      expose-session-attributes: false
      expose-spring-macro-helpers: false
      suffix: .ftl
      template-loader-path: classpath:/templates
  mail:
      host: smtp.qq.com
      password: uuvlpmhvwqaqbdha
      username: 986849363@qq.com
      port: 587
      test-connection: true
      protocol: smtp
      default-encoding: UTF-8
      properties:
          mail.smtp.socketFactory.fallback : true
          mail.smtp.starttls.enable: true


